<a href="https://colab.research.google.com/github/Olga-Lyt/DTA-2026/blob/main/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [ ]:
import numpy as np

# Твій код:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])

print("Temps: ", temps)

print(temps.ndim)
print(temps.shape)
print(temps.size)
print(temps.dtype)



Temps:  [-5 -4  2 10 17 21 23 22 16  9  2 -3]
1
(12,)
12
int64


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [ ]:
# Твій код:
plan = np.full((3, 4), 50)
print(plan)
print(plan.shape)
print(plan.size)

bonus = np.full((3, 4), 0)
print(bonus, "\n")

print(plan + bonus)

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
(3, 4)
12
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [ ]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("Продажі першого тижня: ", sales[:7])
print("Продажі другого тижня: ", sales[7:])
print("Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день: ", sales[[5,6,12,13]])
print("Продажі через день, починаючи з першого: ", sales[[0,2,4,6,8,10,12]])
print("Масив у зворотному порядку: ", sales[::-1])




Продажі першого тижня:  [320 415 290 480 350 620 580]
Продажі другого тижня:  [310 440 305 510 370 650 595]
Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день:  [620 580 650 595]
Продажі через день, починаючи з першого:  [320 290 350 580 440 510 650]
Масив у зворотному порядку:  [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [ ]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
print("Всі оцінки Олени: ", grades[0, :])
print("Оцінки всіх студентів з 3-го предмету: ", grades[:, 2])
print("Оцінки Максима та Ані з предметів 2–4: ", grades[1:3, 1:4])
print("Оцінки останнього студента з останнього предмету: ", grades[-1, -1])

Всі оцінки Олени:  [85 72 91 78 88]
Оцінки всіх студентів з 3-го предмету:  [91 74 82 68]
Оцінки Максима та Ані з предметів 2–4:  [[88 74 95]
 [65 82 70]]
Оцінки останнього студента з останнього предмету:  79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [ ]:
import numpy as np

prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
exchange_rate = 41.5
prices_uah = np.round(prices_usd * exchange_rate, 2)
print(f"Ціни в гривнях: {prices_uah}")

vat_rate = 1.2
prices_with_vat = np.round(prices_uah * vat_rate, 2)
print(f"Ціни з ПДВ: {prices_with_vat}")

min_price_vat = np.min(prices_with_vat)
max_price_vat = np.max(prices_with_vat)
mean_price_vat = np.round(np.mean(prices_with_vat), 2)
print(f"Мінімальна ціна з ПДВ: {min_price_vat} UAH")
print(f"Максимальна ціна з ПДВ: {max_price_vat} UAH")
print(f"Середня ціна з ПДВ: {mean_price_vat} UAH")

total_cart_value = np.round(np.sum(prices_with_vat), 2)
print(f"Загальна вартість кошика з ПДВ: {total_cart_value} UAH")

Ціни в гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Мінімальна ціна з ПДВ: 398.4 UAH
Максимальна ціна з ПДВ: 6225.0 UAH
Середня ціна з ПДВ: 2151.57 UAH
Загальна вартість кошика з ПДВ: 15061.0 UAH


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [ ]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:

total_cost_per_item = quantity * cost_each
print(f"Загальна вартість кожного товару: {total_cost_per_item}")

total_stock_value = np.sum(total_cost_per_item)
print(f"Загальна вартість всього складу: {total_stock_value} UAH")

max_value_index = np.argmax(total_cost_per_item)
max_value_item_name = names[max_value_index]
print(f"Товар з найбільшою сумарною вартістю: {max_value_item_name} ({total_cost_per_item[max_value_index]} UAH)")

min_value_index = np.argmin(total_cost_per_item)
min_value_item_name = names[min_value_index]
print(f"Товар з найменшою сумарною вартістю: {min_value_item_name} ({total_cost_per_item[min_value_index]} UAH)")

mean_item_value = np.round(np.mean(total_cost_per_item), 2)
print(f"Середня вартість одного найменування на складі: {mean_item_value} UAH")

Загальна вартість кожного товару: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість всього складу: 393000 UAH
Товар з найбільшою сумарною вартістю: Монітор (171000 UAH)
Товар з найменшою сумарною вартістю: Зошит (13500 UAH)
Середня вартість одного найменування на складі: 56142.86 UAH


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [ ]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:

on_time_orders = delivery_time[delivery_time <= 30]
print(f"Замовлення, виконані вчасно: {on_time_orders}")

late_orders = delivery_time[delivery_time > 30]
print(f"Запізнілі замовлення: {late_orders}")

num_on_time = on_time_orders.size
num_late = late_orders.size
print(f"Кількість вчасних замовлень: {num_on_time}")
print(f"Кількість запізнілих замовлень: {num_late}")

total_orders = delivery_time.size
percentage_late = np.round((num_late / total_orders) * 100, 1)
print(f"Відсоток запізнілих замовлень: {percentage_late}%")

if num_late > 0:
    average_delay = np.round(np.mean(late_orders - 30), 1)
    print(f"Середня затримка серед запізнілих замовлень: {average_delay} хв")
else:
    print("Запізнілих замовлень немає.")

Замовлення, виконані вчасно: [22 28 19 27 24 26 18 29 23 20]
Запізнілі замовлення: [35 41 55 33 48 31 52 38 44 36]
Кількість вчасних замовлень: 10
Кількість запізнілих замовлень: 10
Відсоток запізнілих замовлень: 50.0%
Середня затримка серед запізнілих замовлень: 11.3 хв


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [ ]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:

monthly_average_sales = np.mean(daily)
days_above_average = daily[daily > monthly_average_sales]
print(f"Дні з продажами вище середнього ({monthly_average_sales:.2f}): {days_above_average}")

num_days_above_average = days_above_average.size
print(f"Кількість днів з продажами вище середнього: {num_days_above_average}")

status = np.where(daily > monthly_average_sales, 'Гарний день', 'Звичайний день')

print("\nПерші 10 днів (продажі та статус):")
for i in range(10):
    print(f"День {i+1}: Продажі = {daily[i]}, Статус = {status[i]}")

Дні з продажами вище середнього (434.23): [535 800 714 566 558 472 763 761 869 443 591 513 485 559]
Кількість днів з продажами вище середнього: 14

Перші 10 днів (продажі та статус):
День 1: Продажі = 202, Статус = Звичайний день
День 2: Продажі = 535, Статус = Гарний день
День 3: Продажі = 370, Статус = Звичайний день
День 4: Продажі = 206, Статус = Звичайний день
День 5: Продажі = 171, Статус = Звичайний день
День 6: Продажі = 800, Статус = Гарний день
День 7: Продажі = 120, Статус = Звичайний день
День 8: Продажі = 714, Статус = Гарний день
День 9: Продажі = 221, Статус = Звичайний день
День 10: Продажі = 566, Статус = Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [ ]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:

hourly_matrix = hourly.reshape(6, 4)
print(f"Матриця 6x4 (продажі по годинах):\n{hourly_matrix}")

block_sums = np.sum(hourly_matrix, axis=1)
print(f"\nСума продажів у кожному 4-годинному блоці: {block_sums}")

sorted_hourly = np.sort(hourly)
print(f"\nВідсортований 1D масив (зростання): {sorted_hourly}")

sorted_indices = np.argsort(hourly)
print(f"\nІндекси годин відсортованих за зростанням продажів: {sorted_indices}")


top_3_indices = np.argsort(hourly)[-3:]

top_3_hours = top_3_indices + 1
print(f"\nТоп-3 найпродуктивніших години (номер години, рахуючи з 0): {top_3_indices}")
print(f"\nТоп-3 найпродуктивніших години (номер години, рахуючи з 1): {top_3_hours}")

Матриця 6x4 (продажі по годинах):
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]

Сума продажів у кожному 4-годинному блоці: [ 28  66 235 240 257 112]

Відсортований 1D масив (зростання): [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]

Індекси годин відсортованих за зростанням продажів: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]

Топ-3 найпродуктивніших години (номер години, рахуючи з 0): [19 12 18]

Топ-3 найпродуктивніших години (номер години, рахуючи з 1): [20 13 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [ ]:
np.random.seed(99)

ages = np.random.randint(18, 66, size=50)
print(f"Масив віку клієнтів (перші 10): {ages[:10]}...")

scores = np.round(np.random.normal(loc=7, scale=1.5, size=50), 1)
print(f"\nМасив оцінок задоволеності (без обрізки, перші 10): {scores[:10]}...")

scores_clipped = np.clip(scores, 1, 10)
print(f"Масив оцінок задоволеності (з обрізкою, перші 10): {scores_clipped[:10]}...")

mean_age = np.mean(ages)
print(f"\nСередній вік клієнтів: {mean_age:.2f}")

mean_score = np.mean(scores_clipped)
print(f"Середня оцінка задоволеності: {mean_score:.2f}")

satisfied_clients = scores_clipped[scores_clipped >= 8]
num_satisfied = satisfied_clients.size
print(f"Кількість клієнтів з оцінкою >= 8: {num_satisfied}")

percentage_satisfied = np.round((num_satisfied / scores_clipped.size) * 100, 1)
print(f"Відсоток задоволених клієнтів: {percentage_satisfied}%")

Масив віку клієнтів (перші 10): [19 53 58 27 58 36 22 23 19 41]...

Масив оцінок задоволеності (без обрізки, перші 10): [5.7 6.4 5.7 9.2 5.5 6.1 6.8 7.9 4.8 8.8]...
Масив оцінок задоволеності (з обрізкою, перші 10): [5.7 6.4 5.7 9.2 5.5 6.1 6.8 7.9 4.8 8.8]...

Середній вік клієнтів: 41.80
Середня оцінка задоволеності: 6.87
Кількість клієнтів з оцінкою >= 8: 10
Відсоток задоволених клієнтів: 20.0%


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [ ]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [ ]:
# Твій код:

total_revenue = np.sum(sales_56)
print(f"Загальна виручка за 56 днів: {total_revenue} грн")

daily_average_revenue = np.round(np.mean(sales_56), 2)
print(f"Середньоденна виручка: {daily_average_revenue} грн")

min_daily_sales = np.min(sales_56)
max_daily_sales = np.max(sales_56)
print(f"Мінімальний денний продаж: {min_daily_sales} грн")
print(f"Максимальний денний продаж: {max_daily_sales} грн")

sales_std_dev = np.round(np.std(sales_56), 2)
print(f"Стандартне відхилення продажів: {sales_std_dev} грн")

Загальна виручка за 56 днів: 31819 грн
Середньоденна виручка: 568.2 грн
Мінімальний денний продаж: 222 грн
Максимальний денний продаж: 1072 грн
Стандартне відхилення продажів: 195.52 грн


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [ ]:
# Твій код:

sales_matrix = sales_56.reshape(8, 7)
print(f"Матриця продажів 8x7:\n{sales_matrix}")

weekly_revenue = np.sum(sales_matrix, axis=1)
print(f"\nВиручка по тижнях: {weekly_revenue} грн")

best_week_index = np.argmax(weekly_revenue)
best_week_number = best_week_index + 1
best_week_revenue = weekly_revenue[best_week_index]
print(f"\nНайкращий тиждень: Тиждень {best_week_number} з виручкою {best_week_revenue} грн")

daily_average_per_weekday = np.round(np.mean(sales_matrix, axis=0), 2)
print(f"\nСередньоденна виручка по днях тижня (Пн-Нд): {daily_average_per_weekday} грн")

most_profitable_day_index = np.argmax(daily_average_per_weekday)
print(f"\nНайприбутковіший день тижня (індекс, 0=Пн): {most_profitable_day_index}")

Матриця продажів 8x7:
[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]

Виручка по тижнях: [4555 3921 3563 3546 5036 3300 4228 3670] грн

Найкращий тиждень: Тиждень 5 з виручкою 5036 грн

Середньоденна виручка по днях тижня (Пн-Нд): [520.38 455.5  565.88 607.75 463.75 629.75 734.38] грн

Найприбутковіший день тижня (індекс, 0=Пн): 6


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [ ]:
# Твій код:

weak_days_mask = sales_56 < 400
num_weak_days = np.sum(weak_days_mask)
print(f"Кількість «слабких» днів (продажі < 400 грн): {num_weak_days}")

strong_days_mask = sales_56 > 700
num_strong_days = np.sum(strong_days_mask)
print(f"Кількість «сильних» днів (продажі > 700 грн): {num_strong_days}")

if num_weak_days > 0:
    average_weak_sales = np.round(np.mean(sales_56[weak_days_mask]), 2)
    print(f"Середня виручка у слабкі дні: {average_weak_sales} грн")
else:
    print("Немає слабких днів для розрахунку середньої виручки.")

if num_strong_days > 0:
    average_strong_sales = np.round(np.mean(sales_56[strong_days_mask]), 2)
    print(f"Середня виручка у сильні дні: {average_strong_sales} грн")
else:
    print("Немає сильних днів для розрахунку середньої виручки.")

labels = np.where(sales_56 < 400, 'Слабкий',
                  np.where(sales_56 > 700, 'Сильний', 'Нормальний'))


print("\nПерші 14 днів: продажі та їх мітки:")
for i in range(14):
    print(f"День {i+1}: Продажі = {sales_56[i]}, Мітка = {labels[i]}")

Кількість «слабких» днів (продажі < 400 грн): 12
Кількість «сильних» днів (продажі > 700 грн): 19
Середня виручка у слабкі дні: 302.0 грн
Середня виручка у сильні дні: 785.16 грн

Перші 14 днів: продажі та їх мітки:
День 1: Продажі = 706, Мітка = Сильний
День 2: Продажі = 739, Мітка = Сильний
День 3: Продажі = 748, Мітка = Сильний
День 4: Продажі = 646, Мітка = Нормальний
День 5: Продажі = 383, Мітка = Слабкий
День 6: Продажі = 556, Мітка = Нормальний
День 7: Продажі = 777, Мітка = Сильний
День 8: Продажі = 427, Мітка = Нормальний
День 9: Продажі = 274, Мітка = Слабкий
День 10: Продажі = 522, Мітка = Нормальний
День 11: Продажі = 680, Мітка = Нормальний
День 12: Продажі = 708, Мітка = Сильний
День 13: Продажі = 465, Мітка = Нормальний
День 14: Продажі = 845, Мітка = Сильний


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
